fix(pre-commit): Bump REUSE hook to 6.2.0
This fixes the following CI error:

```text
reuse.report - ERROR - Unexpected error occurred while parsing 'snap/gui/placeholder-icon.png'
NameError: name 'unicode' is not defined
# UNUSED LICENSES
The following licenses are not used:
* LicenseRef-Canonical-Intellectual-Property-Rights-Policy
# READ ERRORS
Could not read:
* snap/gui/placeholder-icon.png
```

Fixes #22.

Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>